services:
  nanokvm-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanokvm-server
    ports:
      - "8080:8080"
    volumes:
      - ./NanoKVM-USB.zip:/app/NanoKVM-USB.zip
    environment:
      - NODE_ENV=production
      - NO_AUDIO=true
    restart: unless-stopped
    networks:
      - nanokvm-usb-network

networks:
  nanokvm-usb-network:
    driver: bridge